### ISSUE TITLE
distant supervision script exists with error

### ISSUE THREAD

**Issue by ahmarz** [may-/cnn-re-tf#6]
Hello, Thank you for the code.

I have been trying to recreate dataset using same instructions here (https://github.com/may-/cnn-re-tf/issues/3#issuecomment-309293662) it works great till the very end and gives the following error :
________________________________________
Traceback (most recent call last):
  File "./distant_supervision.py", line 693, in <module>
    main()
  File "./distant_supervision.py", line 687, in main
    extract_negative()
  File "./distant_supervision.py", line 666, in extract_negative
    subj = '<' + entities[row['subj'].encode('utf-8')][0] + '>'
KeyError: 'Bell\xc3\xaame'
__________________________________________

Any thoughts? thanks in advance

**Comment by may-** [comment]
Hi,

The error message claims your `entities` dictionary doesn't have the key: 'Bell\xc3\xaame'.
I'm not sure what happens there, but it might be an encoding error.
Could you please just skip that example? something like... 

```python
try:
    subj = '<' + entities[row['subj'].encode('utf-8')][0] + '>'
    obj = '<' + entities[row['obj'].encode('utf-8')][0] + '>'
    rel = ['<' + l.strip() + '>' for l in row['rel'].split(',')]
except Exception as e:
    print '\t', e.message
    print '\tskip this sentence:', row['sent']
    continue
```
(line 666-668 in `distant_supervision.py`)

Alternatively, you could sanitise the text more strictly in `sanitize(string)` function (line 52), so that such noises ('\xc3' -> Ã (tilde-A), '\xaa' -> ª (superscript-a)) are excluded. This would be better, I guess, if your data is kind of noisy in general and big enough...

**Comment by ahmarz** [comment]
Thanks its working now 👍
